### ISSUE TITLE
Alphabetical Sort of Item sets?

### ISSUE THREAD

**Issue by karindalziel** [biblibre/omeka-s-module-ItemSetsTree#3]
I can't figure out how the sort is working for the item set tree. It's not by date, although new Item Sets seem to go to the bottom most often, and it's not alphabetical. 

Is there a way to force an alphabetical sort of all Item sets?

**Comment by jajm** [comment]
This was fixed in v0.2.0 (f4ad18047fd5da1b287390c41816f6ceb8d82048)
